### ISSUE TITLE
script simplification suggestion/idea

### ISSUE THREAD

**Issue by ReenigneArcher** [istori1/Easy-Tan#1]
https://github.com/istori1/Easy-Tan/blob/62ddf0eeee62e7b09bdc51c0548ce43d0f8218f8/sunshine-flatpak-installer.sh#L7-L9

You don't need to create a temp file, copy, then delete it.

You can do something like this https://github.com/LizardByte/Sunshine/blob/894cb6507eed5e3317fb91072e3429cbba6f3ab0/packaging/linux/AppImage/AppRun#L50

```bash
echo 'KERNEL=="uinput", GROUP="input", MODE="0660", OPTIONS+="static_node=uinput"' | sudo tee /etc/udev/85-sunshine.rules
```

**Comment by istori1** [comment]
Added to main branch

https://github.com/istori1/Easy-Tan/blob/main/sunshine-flatpak-installer.sh#L7
